In [97]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [99]:
#How many negative numbers are there
def negative(a):
    count = 0
    for n in a:
        if n < 0:
            count += 1        
    print(f"There are",count,"negative numbers")
    
negative(a)

(a < 0).sum()

There are 4 negative numbers


4

In [100]:
#How many positive numbers are there
def positive(a):
    count = 0
    for n in a:
        if n > 0:
            count += 1
    print(f"There are",count,"positive numbers")
positive(a)

(a > 0).sum()

There are 5 positive numbers


5

In [102]:
#How many even positive numbers are there
def positive_even(a):
    count = 0
    for n in a:
        if n > 0 and n % 2 == 0:
            count += 1
    print(f"There are",count,"even positive numbers")
    
positive_even(a)

len(a[(a > 0) & (a % 2 == 0)])

There are 3 even positive numbers


3

In [107]:
#If you were to add 3 to each data point, how many positive numbers would there be?
b = a + 3
positive(b)
len(b[(b > 0)])

There are 10 positive numbers


10

In [108]:
#If you squared each number, what would the new mean and standard deviation be?
b = a*a #squaring each number
average = b.mean() #the new mean
standard_dev = round(b.std(), 4) #standard deviation, rounding to four digits
print(f"The new mean would be: ",average)
print(f"The standard deviation would be: ",standard_dev)


The new mean would be:  74.0
The standard deviation would be:  144.0243


In [23]:
#Center the data set.
def center_data(a):
    average = a.mean()
    centered = a - average # subtract the mean from each data point
    check_centered = centered.mean() #The data is adjusted such that the mean is 0.
    print(f"The data's new mean is:, ",check_centered)
    print(f"The data has been centered as such: ",centered)

center_data(a)


The data's new mean is:,  0.0
The data has been centered as such:  [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [24]:
#Calculate the z-score for each data point.

def z_score(a):
    average = a.mean() #the mean
    standard_dev = a.std()
    z_scored = ((a - average)/standard_dev)
    print(f"The z-score for each data point is: ",z_scored)
    
z_score(a)
    


The z-score for each data point is:  [ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [ ]:
#### More Numpy Practice ####

In [112]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [76]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
print(sum_of_a)

55


In [80]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)
print(min_of_a)

1


In [79]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(a)
print(max_of_a)


10


In [113]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = a.mean()
print(mean_of_a)


5.5


In [115]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
#from itertools import permutations
#product_of_a = list(permutations(a))
#print(f"The product of multiplying all t he numbers in the above list together are: ",product_of_a)

product_of_a = 1
for n in a:
    product_of_a *= a
    print(product_of_a * a)


[  1   4   9  16  25  36  49  64  81 100]
[   1    8   27   64  125  216  343  512  729 1000]
[    1    16    81   256   625  1296  2401  4096  6561 10000]
[     1     32    243   1024   3125   7776  16807  32768  59049 100000]
[      1      64     729    4096   15625   46656  117649  262144  531441
 1000000]
[       1      128     2187    16384    78125   279936   823543  2097152
  4782969 10000000]
[        1       256      6561     65536    390625   1679616   5764801
  16777216  43046721 100000000]
[         1        512      19683     262144    1953125   10077696
   40353607  134217728  387420489 1000000000]
[          1        1024       59049     1048576     9765625    60466176
   282475249  1073741824  3486784401 10000000000]
[           1         2048       177147      4194304     48828125
    362797056   1977326743   8589934592  31381059609 100000000000]


In [160]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = a * a
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = np.where(a % 2 == 0)

print(odds_in_a)

# odds_in_a = [num for num in a if num % 2 == 1] This is how you do the short way WITHOUT A FOR loop AND WITHOUT NUMPY

(array([1, 3, 5, 7, 9]),)


In [13]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = np.where(a % 2 != 0)

print(evens_in_a)


(array([0, 2, 4, 6, 8]),)


In [118]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [119]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = b.sum()

#sum_of_b = sum(b[0] + b[1])
#print(sum_of_b)
sum_of_b

33

In [120]:
# Exercise 2 - refactor the following to use numpy. 
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

min_of_b = b.min()

#all_of_b = (b[0] + b[1])
#min_of_b = min(all_of_b)
print(min_of_b)




3


In [121]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
#max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = b.max()
#all_of_b = (b[0] + b[1])
#max_of_b = max(all_of_b)
print(max_of_b)


8


In [123]:
#Exercise 4 - refactor the following using numpy to find the mean of b
#mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
b.mean()


5.5

In [126]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
#product_of_b = 1
#for row in b:
#    for number in row:
#        product_of_b *= number

product_of_b = np.prod(b)
print(product_of_b)


20160


In [127]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
b ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [130]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
print(odds_in_b)

b[b % 2 == 1]

[3, 5, 7]


array([3, 5, 7])

In [131]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
b[b%2 != 1]

array([4, 6, 8])

In [61]:
# Exercise 9 - print out the shape of the array b.

b.shape


(2, 3)

In [66]:
# Exercise 10 - transpose the array b.
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [72]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [73]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [76]:
## Setup 3
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [134]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.


min_of_c = c.min()
print(f"The min of array c is: ",min_of_c)


max_of_c = c.max()
print(f"The max of array c is: ",max_of_c)

sum_of_c = c.sum()
print(f"The sum of array c is: ",sum_of_c)


product_of_c = np.prod(c)
print(f" The product of array c is: ",product_of_c)


The min of array c is:  1
The max of array c is:  9
The sum of array c is:  45
 The product of array c is:  362880


In [79]:
# Exercise 2 - Determine the standard deviation of c.

standard_dev = round(c.std(), 4) #standard deviation, rounding to four digits

print(f"The standard deviation would be: ",standard_dev)

The standard deviation would be:  2.582


In [135]:
# Exercise 3 - Determine the variance of c.

c.var()

6.666666666666667

In [80]:
# Exercise 4 - Print out the shape of the array c
c.shape


(3, 3)

In [83]:
# Exercise 5 - Transpose c and print out transposed result.
c.transpose()


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [136]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [92]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
c_c = c.transpose()
l = c * c_c
a = l[0]
b = l[1]
d = l[2]
k = a + b + d
m = sum(k)
print(m)


261


In [140]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

np.prod(c * c.T)

131681894400

In [143]:
## Setup 4
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [146]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [147]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [148]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [149]:
# Exercise 4 - Find all the negative numbers in d


d[(d < 0)]


array([-90, -30, -45, -45])

In [150]:
# Exercise 5 - Find all the positive numbers in d
d[(d > 0)]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [154]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [159]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [151]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [152]:
# Exercise 9 - Transpose and then print out the shape of d.
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [153]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])